services:
  web:
    build: .
    ports:
      - "8777:8777"
    image: "sjamberu/world_of_games:1.0"
    environment:
      FLASK_APP: WorldOfGames
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8777
    secrets:
      - APIKEY
secrets:
  APIKEY:
    file: freecurrencyapi.txt
