services:
  web:
    build: .
    ports:
      - "5000:5000"
    image: "sjamberu/world_of_games:1.0"
    environment:
      FLASK_APP: World Of Games
      FLASK_ENV: "development"
      FLASK_HOST: 0.0.0.0
    secrets:
      - APIKEY
    develop:
      watch:
        - action: sync
          path: .
          target: "../World Of Games"
        - action: rebuild
          path: ../World Of Games
secrets:
  APIKEY:
    file: freecurrencyapi.txt